#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_lasp" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_lasp:
    name: $DEFAULT_NETWORK

services:
  #`zabbix-snmptraps:` определяет службу Docker для SNMP-ловушек Zabbix. Он определяет образ для использования, переменные окружения, ограничения ресурсов, порты для открытия, тома для монтирования и сеть для использования. Также задается имя контейнера и политика перезапуска.
  zabbix-snmptraps:
    #Установка ограничений и резервирования ресурсов для службы Docker. В частности, он ограничивает использование CPU до 0,50 и памяти до 256 МБ, при этом резервируя для службы минимум 0,25 CPU и 128 МБ памяти.
    deploy:
      resources:
        #Установка ограничений на ресурсы для Docker-сервиса `zabbix-snmptraps`. В частности, он ограничивает использование процессора до 0.50 и памяти до 256 МБ.
        limits:
          cpus: "0.50"
          memory: "256M"
        #Резервирование минимум 0,25 CPU и 128MB памяти для Docker-сервиса `zabbix-snmptraps`. Это означает, что даже если ресурсы недоступны, сервису будет гарантировано наличие хотя бы этих минимальных ресурсов.
        reservations:
          cpus: "0.25"
          memory: "128M"
    #`env_file: - "zabbix.env"` задает файл с именем "zabbix.env", содержащий переменные окружения, которые будут использоваться службой Docker `zabbix-snmptraps`. Файл должен быть расположен в том же каталоге, что и файл docker-compose.yml.
    env_file:
      - "zabbix.env"
    #`image: zabbix/zabbix-snmptraps` - это указание образа Docker для службы `zabbix-snmptraps`. Он указывает Docker извлечь образ `zabbix-snmptraps` из реестра Docker Hub и использовать его для создания контейнеров для сервиса.
    image: zabbix/zabbix-snmptraps
    #`labels` - это раздел в файле Docker Compose, который позволяет добавлять метаданные к контейнерам Docker. В данном случае метки содержат информацию о службе SNMP-ловушек Zabbix, такую как ее описание, компания, компонент и операционная система. Эти метки можно использовать для организации, поиска и фильтрации контейнеров Docker.
    labels:
      - "com.zabbix.description=Zabbix snmptraps"
      - "com.zabbix.company=Zabbix LLC"
      - "com.zabbix.component=snmptraps"
      - "com.zabbix.os=linux"
    #`ports: - "162:162/udp"` открывает UDP-порт 162 на хост-машине и перенаправляет его на тот же порт внутри контейнера Docker для службы `zabbix-snmptraps`. Это позволяет службе получать SNMP-ловушки, отправленные на IP-адрес хост-машины по порту 162.
    ports:
      - "162:162/udp"
    #`restart: always` устанавливает политику перезапуска для службы Docker `zabbix-snmptraps`. Это означает, что если контейнер остановится или разрушится по какой-либо причине, Docker автоматически перезапустит его.
    restart: always
    # В разделе `volumes` определяются два монтирования томов для Docker-сервиса `zabbix-snmptraps`. Первый том mount `- "./zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw"` монтирует локальный каталог `./zabbix/snmptraps` в каталог контейнера `/var/lib/zabbix/snmptraps` с правами чтения и записи (`rw`). Это позволяет хранить SNMP-ловушки Zabbix на хост-машине и сохранять их даже при перезапуске или воссоздании контейнера. Второе монтирование тома `- "./zabbix/mibs:/usr/share/snmp/mibs:ro"` монтирует локальный каталог `./zabbix/mibs` в каталог контейнера `/usr/share/snmp/mibs` с правами только для чтения (`ro`). Это позволяет контейнеру получить доступ к файлам SNMP MIB, расположенным на хост-машине.
    volumes:
      #`- "./zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw"` определяет монтирование тома для Docker-сервиса `zabbix-snmptraps`. Он монтирует локальный каталог `./zabbix/snmptraps` в каталог контейнера `/var/lib/zabbix/snmptraps` с разрешениями на чтение и запись (`rw`). Это позволяет хранить SNMP-ловушки Zabbix на хост-машине и сохранять их даже при перезапуске или воссоздании контейнера.
      - "./zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw"
      #`- "./zabbix/mibs:/usr/share/snmp/mibs:ro"` определяет монтирование тома для службы Docker `zabbix-snmptraps`. Он монтирует локальный каталог `./zabbix/mibs` в каталог контейнера `/usr/share/snmp/mibs` с разрешениями только для чтения (`ro`). Это позволяет контейнеру получить доступ к файлам SNMP MIB, расположенным на хост-машине.
      - "./zabbix/mibs:/usr/share/snmp/mibs:ro"
    #`container_name: zabbix-snmptraps` задает пользовательское имя для контейнера Docker, который будет создан для службы `zabbix-snmptraps`. Это имя будет "zabbix-snmptraps" вместо имени по умолчанию, генерируемого Docker. Это может быть полезно для идентификации и управления конкретными контейнерами в среде Docker.
    container_name: zabbix-snmptraps
    #`networks: - "docker_net"` указывает, что Docker-сервис `zabbix-snmptraps` должен быть подключен к сети Docker с именем `docker_net`. Это позволяет сервису взаимодействовать с другими сервисами в той же сети и обеспечивает изоляцию и безопасность сети.
    networks:
      - "docker_net"
